#!/usr/bin/env bash

# Install UFW (if not installed)
sudo apt-get install -y ufw


sudo ufw default deny incoming
sudo ufw default allow outgoing


# allow port 22/tcp connection
sudo ufw allow 22/tcp
# allow port 443/tcp connection
sudo ufw allow 443/tcp
# allow port 88/tcp connection
sudo ufw allow 80/tcp
# enable ufw firewall
sudo ufw enable 
sudo ufw status