#!/usr/bin/env bash
# 1. 1. Run Nginx as Nginx
sed -i 's/user\s*[^;]*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*[^;]*;/listen 8080;/' /etc/nginx/sites-available/default
nginx
pgrep -af nginx
nc -z 0 8080
